### ISSUE TITLE
Images folder does not exist in dist

### ISSUE THREAD

**Issue by sshivananda** [Monte9/react-native-ratings#145]
Introduced in 8.0.1

```
error Unable to resolve module `./images/star.png` from `node_modules/react-native-ratings/dist/SwipeRating.js`: 
```

**Comment by legaciespanda** [comment]
To resolve this issue @sshivananda @jlee0831 @SimenB @chicrock @benwiebe 

**STEP 1**
Goto yourAppFolder/node_modules\react-native-ratings\dist\SwipeRating.js
replace line 5 -8 with the code below
```
const STAR_IMAGE = require("../src/images/star.png");
const HEART_IMAGE = require("../src/images/heart.png");
const ROCKET_IMAGE = require("../src/images/rocket.png");
const BELL_IMAGE = require("../src/images/bell.png");
```

**STEP 2**
Goto yourAppFolder/node_modules\react-native-ratings\dist\components\Star.js
replace line 3 -4 with the code below
```
const STAR_IMAGE = require("../../src/images/airbnb-star.png");
const STAR_SELECTED_IMAGE = require("../../src/images/airbnb-star-selected.png");
```

Problem solved.

This issue should be fixed soon

**Comment by khushal87** [comment]
I will have a look at this @sshivananda Can you explain the steps to reproduce?

**Comment by slasho** [comment]
> I will have a look at this @sshivananda Can you explain the steps to reproduce?

yarn add react-native-ratings

import it and you got the error

**Comment by MBach** [comment]
Just tried with 8.0.2 release, with cleaned folders (node_modules / android build), the bug is still here.

**Comment by sshivananda** [comment]
@MBach can you try with v8.0.3 - I think it was an issue with the way the package was published : I republished it again

**Comment by MBach** [comment]
Seems fine with v8.0.3!
